{% set name = "pydefect" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydefect-{{ version }}.tar.gz
  sha256: 1dfde8a0c382fd9a82f97b09304a285cee5b709d294a5b5308f3c37a1f732e65
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pydefect = pydefect.cli.main:main
    - pydefect_util = pydefect.cli.main_util:main
    - pydefect_vasp = pydefect.cli.vasp.main_vasp:main
    - pydefect_vasp_util = pydefect.cli.vasp.main_vasp_util:main
    - pydefect_print = pydefect.cli.main_print_json:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - monty
    - pymatgen
    - vise
    - tabulate
    - adjusttext
    - matplotlib-label-lines

test:
  imports:
    - pydefect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kumagai-group/pydefect
  summary: Integrated environment for first-principles point-defect calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
