{% set name = "pydefect" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydefect-{{ version }}.tar.gz
  sha256: aa49170296eee752bf68f70ca685945c6cd227ea043af6e21e8a41fad5071f54
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pydefect = pydefect.cli.main:main
    - pydefect_util = pydefect.cli.main_util:main
    - pydefect_vasp = pydefect.cli.vasp.main_vasp:main
    - pydefect_vasp_util = pydefect.cli.vasp.main_vasp_util:main
    - pydefect_print = pydefect.cli.main_print_json:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - monty
    - pymatgen
    - vise
    - tabulate
    - adjusttext
    - matplotlib-label-lines

test:
  imports:
    - pydefect
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kumagai-group/pydefect
  summary: Integrated environment for first-principles point-defect calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
