schema_version: 1

context:
  name: pydefect
  version: 0.10.1
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydefect-${{ version }}.tar.gz
  sha256: c97e61ef132b958bbd4c34d0e080f658aba4f134b2f89f203e7517128a4a8bd6
  patches:
    - requirements.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pydefect = pydefect.cli.main:main
      - pydefect_util = pydefect.cli.main_util:main
      - pydefect_vasp = pydefect.cli.vasp.main_vasp:main
      - pydefect_vasp_util = pydefect.cli.vasp.main_vasp_util:main
      - pydefect_print = pydefect.cli.main_print_json:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - scikit-image
    - python >=${{ python_min }}
    - numpy
    - monty
    - vise
    - tabulate
    - adjusttext
    - matplotlib-label-lines
    - pymatgen-core
tests:
  - python:
      imports:
        - pydefect
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Integrated environment for first-principles point-defect calculations
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/kumagai-group/pydefect

extra:
  recipe-maintainers:
    - jan-janssen
